### Test
GET http://localhost:8080/rest/animations/test

### save an animation
POST http://localhost:8080/rest/animations
Content-Type: application/json

{
  "title": "Test",
  "frames": []
}

#### Get all animations
#GET http://localhost:8080/rest/animations/
#
