spring:
  liquibase:
    enabled: false
  datasource:
    schmitz-sandbox:
      jdbc-url: jdbc:postgresql://localhost:5432/schmitz_sandbox
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
#    change-log: classpath:database/changelog.sql
