spring:
  liquibase:
    #    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    schmitz-sandbox:
      jdbc-url: jdbc:postgresql://database:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      #      jdbc-url: jdbc:postgresql://database:5432/postgres



